integrable_function_space.pdf: ../*.tex ../trademark.pdf *.tex
	pdflatex integrable_function_space.tex
	make defs

make:
	make integrable_function_space.pdf

open: integrable_function_space.pdf
	open integrable_function_space.pdf

defs: integrable_function_space.tex
	defs integrable_function_space.tex
