all: ../graph.tmpl ../clip.go 
	graph --csv data_fitting.csv --tmpl ../graph.tmpl > data_fitting.graphviz
	dot data_fitting.graphviz -o data_fitting.pdf -T pdf
	graph --csv data_set.csv --tmpl ../graph.tmpl > data_set.graphviz
	dot data_set.graphviz -o data_set.pdf -T pdf
	graph --csv direct_products.csv --tmpl ../graph.tmpl > direct_products.graphviz
	dot direct_products.graphviz -o direct_products.pdf -T pdf
	graph --csv empirical_distribution.csv --tmpl ../graph.tmpl > empirical_distribution.graphviz
	dot empirical_distribution.graphviz -o empirical_distribution.pdf -T pdf
	graph --csv functional_analysis.csv --tmpl ../graph.tmpl > functional_analysis.graphviz
	dot functional_analysis.graphviz -o functional_analysis.pdf -T pdf
	graph --csv metric_completion.csv --tmpl ../graph.tmpl > metric_completion.graphviz
	dot metric_completion.graphviz -o metric_completion.pdf -T pdf
	graph --csv bounded_linear_functions.csv --tmpl ../graph.tmpl > bounded_linear_functions.graphviz
	dot bounded_linear_functions.graphviz -o bounded_linear_functions.pdf -T pdf
	graph --csv cardinality.csv --tmpl ../graph.tmpl > cardinality.graphviz
	dot cardinality.graphviz -o cardinality.pdf -T pdf
	graph --csv mutual_information.csv --tmpl ../graph.tmpl > mutual_information.graphviz
	dot mutual_information.graphviz -o mutual_information.pdf -T pdf
	graph --csv measure_space.csv --tmpl ../graph.tmpl > measure_space.graphviz
	dot measure_space.graphviz -o measure_space.pdf -T pdf
	graph --csv metrics.csv --tmpl ../graph.tmpl > metrics.graphviz
	dot metrics.graphviz -o metrics.pdf -T pdf
	graph --csv orthogonal_complements.csv --tmpl ../graph.tmpl > orthogonal_complements.graphviz
	dot orthogonal_complements.graphviz -o orthogonal_complements.pdf -T pdf
	graph --csv real_sequences.csv --tmpl ../graph.tmpl > real_sequences.graphviz
	dot real_sequences.graphviz -o real_sequences.pdf -T pdf
	graph --csv triangle_equality.csv --tmpl ../graph.tmpl > triangle_equality.graphviz
	dot triangle_equality.graphviz -o triangle_equality.pdf -T pdf
	graph --csv groups.csv --tmpl ../graph.tmpl > groups.graphviz
	dot groups.graphviz -o groups.pdf -T pdf
	graph --csv identity.csv --tmpl ../graph.tmpl > identity.graphviz
	dot identity.graphviz -o identity.pdf -T pdf
	graph --csv functionals.csv --tmpl ../graph.tmpl > functionals.graphviz
	dot functionals.graphviz -o functionals.pdf -T pdf
	graph --csv natural_numbers.csv --tmpl ../graph.tmpl > natural_numbers.graphviz
	dot natural_numbers.graphviz -o natural_numbers.pdf -T pdf
	graph --csv span.csv --tmpl ../graph.tmpl > span.graphviz
	dot span.graphviz -o span.pdf -T pdf
	graph --csv subsets.csv --tmpl ../graph.tmpl > subsets.graphviz
	dot subsets.graphviz -o subsets.pdf -T pdf
	graph --csv functions.csv --tmpl ../graph.tmpl > functions.graphviz
	dot functions.graphviz -o functions.pdf -T pdf
	graph --csv integer_numbers.csv --tmpl ../graph.tmpl > integer_numbers.graphviz
	dot integer_numbers.graphviz -o integer_numbers.pdf -T pdf
	graph --csv inner_products.csv --tmpl ../graph.tmpl > inner_products.graphviz
	dot inner_products.graphviz -o inner_products.pdf -T pdf
	graph --csv real_numbers.csv --tmpl ../graph.tmpl > real_numbers.graphviz
	dot real_numbers.graphviz -o real_numbers.pdf -T pdf
	graph --csv function_composition.csv --tmpl ../graph.tmpl > function_composition.graphviz
	dot function_composition.graphviz -o function_composition.pdf -T pdf
	graph --csv graphs.csv --tmpl ../graph.tmpl > graphs.graphviz
	dot graphs.graphviz -o graphs.pdf -T pdf
	graph --csv probability_events.csv --tmpl ../graph.tmpl > probability_events.graphviz
	dot probability_events.graphviz -o probability_events.pdf -T pdf
	graph --csv real_convergence.csv --tmpl ../graph.tmpl > real_convergence.graphviz
	dot real_convergence.graphviz -o real_convergence.pdf -T pdf
	graph --csv real_uniform_continuity.csv --tmpl ../graph.tmpl > real_uniform_continuity.graphviz
	dot real_uniform_continuity.graphviz -o real_uniform_continuity.pdf -T pdf
	graph --csv supervised_learning.csv --tmpl ../graph.tmpl > supervised_learning.graphviz
	dot supervised_learning.graphviz -o supervised_learning.pdf -T pdf
	graph --csv function_inverses.csv --tmpl ../graph.tmpl > function_inverses.graphviz
	dot function_inverses.graphviz -o function_inverses.pdf -T pdf
	graph --csv metric_completeness.csv --tmpl ../graph.tmpl > metric_completeness.graphviz
	dot metric_completeness.graphviz -o metric_completeness.pdf -T pdf
	graph --csv complete_inner_product_decomposition.csv --tmpl ../graph.tmpl > complete_inner_product_decomposition.graphviz
	dot complete_inner_product_decomposition.graphviz -o complete_inner_product_decomposition.pdf -T pdf
	graph --csv fields.csv --tmpl ../graph.tmpl > fields.graphviz
	dot fields.graphviz -o fields.pdf -T pdf
	graph --csv linear_combinations.csv --tmpl ../graph.tmpl > linear_combinations.graphviz
	dot linear_combinations.graphviz -o linear_combinations.pdf -T pdf
	graph --csv linear_functions.csv --tmpl ../graph.tmpl > linear_functions.graphviz
	dot linear_functions.graphviz -o linear_functions.pdf -T pdf
	graph --csv operations.csv --tmpl ../graph.tmpl > operations.graphviz
	dot operations.graphviz -o operations.pdf -T pdf
	graph --csv sequences.csv --tmpl ../graph.tmpl > sequences.graphviz
	dot sequences.graphviz -o sequences.pdf -T pdf
	graph --csv bounded_linear_continuous.csv --tmpl ../graph.tmpl > bounded_linear_continuous.graphviz
	dot bounded_linear_continuous.graphviz -o bounded_linear_continuous.pdf -T pdf
	graph --csv bounded_linear_norm.csv --tmpl ../graph.tmpl > bounded_linear_norm.graphviz
	dot bounded_linear_norm.graphviz -o bounded_linear_norm.pdf -T pdf
	graph --csv vector_bases.csv --tmpl ../graph.tmpl > vector_bases.graphviz
	dot vector_bases.graphviz -o vector_bases.pdf -T pdf
	graph --csv set_specification.csv --tmpl ../graph.tmpl > set_specification.graphviz
	dot set_specification.graphviz -o set_specification.pdf -T pdf
	graph --csv supremum_norm.csv --tmpl ../graph.tmpl > supremum_norm.graphviz
	dot supremum_norm.graphviz -o supremum_norm.pdf -T pdf
	graph --csv entropy.csv --tmpl ../graph.tmpl > entropy.graphviz
	dot entropy.graphviz -o entropy.pdf -T pdf
	graph --csv norm_examples.csv --tmpl ../graph.tmpl > norm_examples.graphviz
	dot norm_examples.graphviz -o norm_examples.pdf -T pdf
	graph --csv sentences.csv --tmpl ../graph.tmpl > sentences.graphviz
	dot sentences.graphviz -o sentences.pdf -T pdf
	graph --csv sets.csv --tmpl ../graph.tmpl > sets.graphviz
	dot sets.graphviz -o sets.pdf -T pdf
	graph --csv conditional_dependency_graph.csv --tmpl ../graph.tmpl > conditional_dependency_graph.graphviz
	dot conditional_dependency_graph.graphviz -o conditional_dependency_graph.pdf -T pdf
	graph --csv distributions.csv --tmpl ../graph.tmpl > distributions.graphviz
	dot distributions.graphviz -o distributions.pdf -T pdf
	graph --csv isometries.csv --tmpl ../graph.tmpl > isometries.graphviz
	dot isometries.graphviz -o isometries.pdf -T pdf
	graph --csv logarithm.csv --tmpl ../graph.tmpl > logarithm.graphviz
	dot logarithm.graphviz -o logarithm.pdf -T pdf
	graph --csv rooted_trees.csv --tmpl ../graph.tmpl > rooted_trees.graphviz
	dot rooted_trees.graphviz -o rooted_trees.pdf -T pdf
	graph --csv solving_equations.csv --tmpl ../graph.tmpl > solving_equations.graphviz
	dot solving_equations.graphviz -o solving_equations.pdf -T pdf
	graph --csv closest_point_property.csv --tmpl ../graph.tmpl > closest_point_property.graphviz
	dot closest_point_property.graphviz -o closest_point_property.pdf -T pdf
	graph --csv egoprox_sequences.csv --tmpl ../graph.tmpl > egoprox_sequences.graphviz
	dot egoprox_sequences.graphviz -o egoprox_sequences.pdf -T pdf
	graph --csv mutual_information_graph.csv --tmpl ../graph.tmpl > mutual_information_graph.graphviz
	dot mutual_information_graph.graphviz -o mutual_information_graph.pdf -T pdf
	graph --csv nash_equilibria.csv --tmpl ../graph.tmpl > nash_equilibria.graphviz
	dot nash_equilibria.graphviz -o nash_equilibria.pdf -T pdf
	graph --csv norm_completeness.csv --tmpl ../graph.tmpl > norm_completeness.graphviz
	dot norm_completeness.graphviz -o norm_completeness.pdf -T pdf
	graph --csv norm_metrics.csv --tmpl ../graph.tmpl > norm_metrics.graphviz
	dot norm_metrics.graphviz -o norm_metrics.pdf -T pdf
	graph --csv norms.csv --tmpl ../graph.tmpl > norms.graphviz
	dot norms.graphviz -o norms.pdf -T pdf
	graph --csv probability_outcomes.csv --tmpl ../graph.tmpl > probability_outcomes.graphviz
	dot probability_outcomes.graphviz -o probability_outcomes.pdf -T pdf
	graph --csv complex_inner_products.csv --tmpl ../graph.tmpl > complex_inner_products.graphviz
	dot complex_inner_products.graphviz -o complex_inner_products.pdf -T pdf
	graph --csv equations.csv --tmpl ../graph.tmpl > equations.graphviz
	dot equations.graphviz -o equations.pdf -T pdf
	graph --csv zero_sum_matrix_games.csv --tmpl ../graph.tmpl > zero_sum_matrix_games.graphviz
	dot zero_sum_matrix_games.graphviz -o zero_sum_matrix_games.pdf -T pdf
	graph --csv real_continuity.csv --tmpl ../graph.tmpl > real_continuity.graphviz
	dot real_continuity.graphviz -o real_continuity.pdf -T pdf
	graph --csv two-player_one-shot_games.csv --tmpl ../graph.tmpl > two-player_one-shot_games.graphviz
	dot two-player_one-shot_games.graphviz -o two-player_one-shot_games.pdf -T pdf
	graph --csv data_matrix.csv --tmpl ../graph.tmpl > data_matrix.graphviz
	dot data_matrix.graphviz -o data_matrix.pdf -T pdf
	graph --csv matrices.csv --tmpl ../graph.tmpl > matrices.graphviz
	dot matrices.graphviz -o matrices.pdf -T pdf
	graph --csv metric_convergence.csv --tmpl ../graph.tmpl > metric_convergence.graphviz
	dot metric_convergence.graphviz -o metric_convergence.pdf -T pdf
	graph --csv metric_dense.csv --tmpl ../graph.tmpl > metric_dense.graphviz
	dot metric_dense.graphviz -o metric_dense.pdf -T pdf
	graph --csv probability_measures.csv --tmpl ../graph.tmpl > probability_measures.graphviz
	dot probability_measures.graphviz -o probability_measures.pdf -T pdf
	graph --csv set_examples.csv --tmpl ../graph.tmpl > set_examples.graphviz
	dot set_examples.graphviz -o set_examples.pdf -T pdf
	graph --csv arithmetic.csv --tmpl ../graph.tmpl > arithmetic.graphviz
	dot arithmetic.graphviz -o arithmetic.pdf -T pdf
	graph --csv cross_entropy.csv --tmpl ../graph.tmpl > cross_entropy.graphviz
	dot cross_entropy.graphviz -o cross_entropy.pdf -T pdf
	graph --csv vectors.csv --tmpl ../graph.tmpl > vectors.graphviz
	dot vectors.graphviz -o vectors.pdf -T pdf
	graph --csv tree-structured_distributions.csv --tmpl ../graph.tmpl > tree-structured_distributions.graphviz
	dot tree-structured_distributions.graphviz -o tree-structured_distributions.pdf -T pdf
	graph --csv distribution_expectation.csv --tmpl ../graph.tmpl > distribution_expectation.graphviz
	dot distribution_expectation.graphviz -o distribution_expectation.pdf -T pdf
	graph --csv graph_cliques.csv --tmpl ../graph.tmpl > graph_cliques.graphviz
	dot graph_cliques.graphviz -o graph_cliques.pdf -T pdf
	graph --csv matrix_games.csv --tmpl ../graph.tmpl > matrix_games.graphviz
	dot matrix_games.graphviz -o matrix_games.pdf -T pdf
	graph --csv set_extension.csv --tmpl ../graph.tmpl > set_extension.graphviz
	dot set_extension.graphviz -o set_extension.pdf -T pdf
	graph --csv tree-structured_distribution_approximation.csv --tmpl ../graph.tmpl > tree-structured_distribution_approximation.graphviz
	dot tree-structured_distribution_approximation.graphviz -o tree-structured_distribution_approximation.pdf -T pdf
	graph --csv algebras.csv --tmpl ../graph.tmpl > algebras.graphviz
	dot algebras.graphviz -o algebras.pdf -T pdf
	graph --csv complex_numbers.csv --tmpl ../graph.tmpl > complex_numbers.graphviz
	dot complex_numbers.graphviz -o complex_numbers.pdf -T pdf
	graph --csv metric_continuity.csv --tmpl ../graph.tmpl > metric_continuity.graphviz
	dot metric_continuity.graphviz -o metric_continuity.pdf -T pdf
	graph --csv metric_space_examples.csv --tmpl ../graph.tmpl > metric_space_examples.graphviz
	dot metric_space_examples.graphviz -o metric_space_examples.pdf -T pdf
	graph --csv zero.csv --tmpl ../graph.tmpl > zero.graphviz
	dot zero.graphviz -o zero.pdf -T pdf
	graph --csv absolute_value.csv --tmpl ../graph.tmpl > absolute_value.graphviz
	dot absolute_value.graphviz -o absolute_value.pdf -T pdf
	graph --csv bounded_functions.csv --tmpl ../graph.tmpl > bounded_functions.graphviz
	dot bounded_functions.graphviz -o bounded_functions.pdf -T pdf
	graph --csv linear_independence.csv --tmpl ../graph.tmpl > linear_independence.graphviz
	dot linear_independence.graphviz -o linear_independence.pdf -T pdf
	graph --csv ordered_pairs.csv --tmpl ../graph.tmpl > ordered_pairs.graphviz
	dot ordered_pairs.graphviz -o ordered_pairs.pdf -T pdf
	graph --csv probability_density_function.csv --tmpl ../graph.tmpl > probability_density_function.graphviz
	dot probability_density_function.graphviz -o probability_density_function.pdf -T pdf
	graph --csv probability_mass_functions.csv --tmpl ../graph.tmpl > probability_mass_functions.graphviz
	dot probability_mass_functions.graphviz -o probability_mass_functions.pdf -T pdf
	graph --csv relations.csv --tmpl ../graph.tmpl > relations.graphviz
	dot relations.graphviz -o relations.pdf -T pdf
	graph --csv set_operations.csv --tmpl ../graph.tmpl > set_operations.graphviz
	dot set_operations.graphviz -o set_operations.pdf -T pdf
	graph --csv conditional_distributions.csv --tmpl ../graph.tmpl > conditional_distributions.graphviz
	dot conditional_distributions.graphviz -o conditional_distributions.pdf -T pdf
	graph --csv inner_product_norms.csv --tmpl ../graph.tmpl > inner_product_norms.graphviz
	dot inner_product_norms.graphviz -o inner_product_norms.pdf -T pdf
	graph --csv subset_algebra.csv --tmpl ../graph.tmpl > subset_algebra.graphviz
	dot subset_algebra.graphviz -o subset_algebra.pdf -T pdf
	graph --csv random_variables.csv --tmpl ../graph.tmpl > random_variables.graphviz
	dot random_variables.graphviz -o random_variables.pdf -T pdf
	graph --csv relative_entropy.csv --tmpl ../graph.tmpl > relative_entropy.graphviz
	dot relative_entropy.graphviz -o relative_entropy.pdf -T pdf
	graph --csv trees.csv --tmpl ../graph.tmpl > trees.graphviz
	dot trees.graphviz -o trees.pdf -T pdf
	graph --csv vector_space_dimension.csv --tmpl ../graph.tmpl > vector_space_dimension.graphviz
	dot vector_space_dimension.graphviz -o vector_space_dimension.pdf -T pdf
	graph --csv marginal_distributions.csv --tmpl ../graph.tmpl > marginal_distributions.graphviz
	dot marginal_distributions.graphviz -o marginal_distributions.pdf -T pdf
	graph --csv orthogonal_vectors.csv --tmpl ../graph.tmpl > orthogonal_vectors.graphviz
	dot orthogonal_vectors.graphviz -o orthogonal_vectors.pdf -T pdf
