all: ../graph.tmpl ../clip.go 
	graph --csv distance.csv --tmpl ../graph.tmpl > distance.graphviz
	dot distance.graphviz -o distance.pdf -T pdf
	graph --csv product_sigma_algebras.csv --tmpl ../graph.tmpl > product_sigma_algebras.graphviz
	dot product_sigma_algebras.graphviz -o product_sigma_algebras.pdf -T pdf
	graph --csv tail_sigma_algebra.csv --tmpl ../graph.tmpl > tail_sigma_algebra.graphviz
	dot tail_sigma_algebra.graphviz -o tail_sigma_algebra.pdf -T pdf
	graph --csv variation_measure.csv --tmpl ../graph.tmpl > variation_measure.graphviz
	dot variation_measure.graphviz -o variation_measure.pdf -T pdf
	graph --csv complex_integrals.csv --tmpl ../graph.tmpl > complex_integrals.graphviz
	dot complex_integrals.graphviz -o complex_integrals.pdf -T pdf
	graph --csv finite_measures.csv --tmpl ../graph.tmpl > finite_measures.graphviz
	dot finite_measures.graphviz -o finite_measures.pdf -T pdf
	graph --csv points.csv --tmpl ../graph.tmpl > points.graphviz
	dot points.graphviz -o points.pdf -T pdf
	graph --csv subsets.csv --tmpl ../graph.tmpl > subsets.graphviz
	dot subsets.graphviz -o subsets.pdf -T pdf
	graph --csv signed_measures.csv --tmpl ../graph.tmpl > signed_measures.graphviz
	dot signed_measures.graphviz -o signed_measures.pdf -T pdf
	graph --csv graph_cliques.csv --tmpl ../graph.tmpl > graph_cliques.graphviz
	dot graph_cliques.graphviz -o graph_cliques.pdf -T pdf
	graph --csv moment_generating_function.csv --tmpl ../graph.tmpl > moment_generating_function.graphviz
	dot moment_generating_function.graphviz -o moment_generating_function.pdf -T pdf
	graph --csv set-builder_notation.csv --tmpl ../graph.tmpl > set-builder_notation.graphviz
	dot set-builder_notation.graphviz -o set-builder_notation.pdf -T pdf
	graph --csv groups.csv --tmpl ../graph.tmpl > groups.graphviz
	dot groups.graphviz -o groups.pdf -T pdf
	graph --csv interval_partitions.csv --tmpl ../graph.tmpl > interval_partitions.graphviz
	dot interval_partitions.graphviz -o interval_partitions.pdf -T pdf
	graph --csv real_continuity.csv --tmpl ../graph.tmpl > real_continuity.graphviz
	dot real_continuity.graphviz -o real_continuity.pdf -T pdf
	graph --csv commutative_operations.csv --tmpl ../graph.tmpl > commutative_operations.graphviz
	dot commutative_operations.graphviz -o commutative_operations.pdf -T pdf
	graph --csv inner_products.csv --tmpl ../graph.tmpl > inner_products.graphviz
	dot inner_products.graphviz -o inner_products.pdf -T pdf
	graph --csv supremum_norm.csv --tmpl ../graph.tmpl > supremum_norm.graphviz
	dot supremum_norm.graphviz -o supremum_norm.pdf -T pdf
	graph --csv topological_sigma_algebra.csv --tmpl ../graph.tmpl > topological_sigma_algebra.graphviz
	dot topological_sigma_algebra.graphviz -o topological_sigma_algebra.pdf -T pdf
	graph --csv distance_asymmetry.csv --tmpl ../graph.tmpl > distance_asymmetry.graphviz
	dot distance_asymmetry.graphviz -o distance_asymmetry.pdf -T pdf
	graph --csv metric_continuity.csv --tmpl ../graph.tmpl > metric_continuity.graphviz
	dot metric_continuity.graphviz -o metric_continuity.pdf -T pdf
	graph --csv sigma_algebra.csv --tmpl ../graph.tmpl > sigma_algebra.graphviz
	dot sigma_algebra.graphviz -o sigma_algebra.pdf -T pdf
	graph --csv borel_sigma_algebra.csv --tmpl ../graph.tmpl > borel_sigma_algebra.graphviz
	dot borel_sigma_algebra.graphviz -o borel_sigma_algebra.pdf -T pdf
	graph --csv expectation_deviation_upper_bound.csv --tmpl ../graph.tmpl > expectation_deviation_upper_bound.graphviz
	dot expectation_deviation_upper_bound.graphviz -o expectation_deviation_upper_bound.pdf -T pdf
	graph --csv simple_integrals.csv --tmpl ../graph.tmpl > simple_integrals.graphviz
	dot simple_integrals.graphviz -o simple_integrals.pdf -T pdf
	graph --csv nets.csv --tmpl ../graph.tmpl > nets.graphviz
	dot nets.graphviz -o nets.pdf -T pdf
	graph --csv correlation.csv --tmpl ../graph.tmpl > correlation.graphviz
	dot correlation.graphviz -o correlation.pdf -T pdf
	graph --csv function_properties.csv --tmpl ../graph.tmpl > function_properties.graphviz
	dot function_properties.graphviz -o function_properties.pdf -T pdf
	graph --csv integrable_function_space.csv --tmpl ../graph.tmpl > integrable_function_space.graphviz
	dot integrable_function_space.graphviz -o integrable_function_space.pdf -T pdf
	graph --csv signed_measure_examples.csv --tmpl ../graph.tmpl > signed_measure_examples.graphviz
	dot signed_measure_examples.graphviz -o signed_measure_examples.pdf -T pdf
	graph --csv vectors.csv --tmpl ../graph.tmpl > vectors.graphviz
	dot vectors.graphviz -o vectors.pdf -T pdf
	graph --csv function_composition.csv --tmpl ../graph.tmpl > function_composition.graphviz
	dot function_composition.graphviz -o function_composition.pdf -T pdf
	graph --csv sets.csv --tmpl ../graph.tmpl > sets.graphviz
	dot sets.graphviz -o sets.pdf -T pdf
	graph --csv algebras.csv --tmpl ../graph.tmpl > algebras.graphviz
	dot algebras.graphviz -o algebras.pdf -T pdf
	graph --csv identity_functions.csv --tmpl ../graph.tmpl > identity_functions.graphviz
	dot identity_functions.graphviz -o identity_functions.pdf -T pdf
	graph --csv zero.csv --tmpl ../graph.tmpl > zero.graphviz
	dot zero.graphviz -o zero.pdf -T pdf
	graph --csv complex_measures.csv --tmpl ../graph.tmpl > complex_measures.graphviz
	dot complex_measures.graphviz -o complex_measures.pdf -T pdf
	graph --csv measure_properties.csv --tmpl ../graph.tmpl > measure_properties.graphviz
	dot measure_properties.graphviz -o measure_properties.pdf -T pdf
	graph --csv metric_balls.csv --tmpl ../graph.tmpl > metric_balls.graphviz
	dot metric_balls.graphviz -o metric_balls.pdf -T pdf
	graph --csv probability_measures.csv --tmpl ../graph.tmpl > probability_measures.graphviz
	dot probability_measures.graphviz -o probability_measures.pdf -T pdf
	graph --csv arithmetic.csv --tmpl ../graph.tmpl > arithmetic.graphviz
	dot arithmetic.graphviz -o arithmetic.pdf -T pdf
	graph --csv identity_elements.csv --tmpl ../graph.tmpl > identity_elements.graphviz
	dot identity_elements.graphviz -o identity_elements.pdf -T pdf
	graph --csv simple_integral_monotonicity.csv --tmpl ../graph.tmpl > simple_integral_monotonicity.graphviz
	dot simple_integral_monotonicity.graphviz -o simple_integral_monotonicity.pdf -T pdf
	graph --csv absolute_value.csv --tmpl ../graph.tmpl > absolute_value.graphviz
	dot absolute_value.graphviz -o absolute_value.pdf -T pdf
	graph --csv area.csv --tmpl ../graph.tmpl > area.graphviz
	dot area.graphviz -o area.pdf -T pdf
	graph --csv cardinality.csv --tmpl ../graph.tmpl > cardinality.graphviz
	dot cardinality.graphviz -o cardinality.pdf -T pdf
	graph --csv complex_numbers.csv --tmpl ../graph.tmpl > complex_numbers.graphviz
	dot complex_numbers.graphviz -o complex_numbers.pdf -T pdf
	graph --csv matroids.csv --tmpl ../graph.tmpl > matroids.graphviz
	dot matroids.graphviz -o matroids.pdf -T pdf
	graph --csv measures.csv --tmpl ../graph.tmpl > measures.graphviz
	dot measures.graphviz -o measures.pdf -T pdf
	graph --csv singular_measures.csv --tmpl ../graph.tmpl > singular_measures.graphviz
	dot singular_measures.graphviz -o singular_measures.pdf -T pdf
	graph --csv metric_space_functions.csv --tmpl ../graph.tmpl > metric_space_functions.graphviz
	dot metric_space_functions.graphviz -o metric_space_functions.pdf -T pdf
	graph --csv variance.csv --tmpl ../graph.tmpl > variance.graphviz
	dot variance.graphviz -o variance.pdf -T pdf
	graph --csv event_independence.csv --tmpl ../graph.tmpl > event_independence.graphviz
	dot event_independence.graphviz -o event_independence.pdf -T pdf
	graph --csv almost_everywhere.csv --tmpl ../graph.tmpl > almost_everywhere.graphviz
	dot almost_everywhere.graphviz -o almost_everywhere.pdf -T pdf
	graph --csv fields.csv --tmpl ../graph.tmpl > fields.graphviz
	dot fields.graphviz -o fields.pdf -T pdf
	graph --csv real_numbers.csv --tmpl ../graph.tmpl > real_numbers.graphviz
	dot real_numbers.graphviz -o real_numbers.pdf -T pdf
	graph --csv set_operations.csv --tmpl ../graph.tmpl > set_operations.graphviz
	dot set_operations.graphviz -o set_operations.pdf -T pdf
	graph --csv integrable_function_spaces.csv --tmpl ../graph.tmpl > integrable_function_spaces.graphviz
	dot integrable_function_spaces.graphviz -o integrable_function_spaces.pdf -T pdf
	graph --csv natural_induction.csv --tmpl ../graph.tmpl > natural_induction.graphviz
	dot natural_induction.graphviz -o natural_induction.pdf -T pdf
	graph --csv random_variables.csv --tmpl ../graph.tmpl > random_variables.graphviz
	dot random_variables.graphviz -o random_variables.pdf -T pdf
	graph --csv random_variable_laws.csv --tmpl ../graph.tmpl > random_variable_laws.graphviz
	dot random_variable_laws.graphviz -o random_variable_laws.pdf -T pdf
	graph --csv relation_properties.csv --tmpl ../graph.tmpl > relation_properties.graphviz
	dot relation_properties.graphviz -o relation_properties.pdf -T pdf
	graph --csv categories.csv --tmpl ../graph.tmpl > categories.graphviz
	dot categories.graphviz -o categories.pdf -T pdf
	graph --csv total_variation_complete.csv --tmpl ../graph.tmpl > total_variation_complete.graphviz
	dot total_variation_complete.graphviz -o total_variation_complete.pdf -T pdf
	graph --csv measure_space.csv --tmpl ../graph.tmpl > measure_space.graphviz
	dot measure_space.graphviz -o measure_space.pdf -T pdf
	graph --csv product_measures.csv --tmpl ../graph.tmpl > product_measures.graphviz
	dot product_measures.graphviz -o product_measures.pdf -T pdf
	graph --csv generated_monotone_class.csv --tmpl ../graph.tmpl > generated_monotone_class.graphviz
	dot generated_monotone_class.graphviz -o generated_monotone_class.pdf -T pdf
	graph --csv image_measures.csv --tmpl ../graph.tmpl > image_measures.graphviz
	dot image_measures.graphviz -o image_measures.pdf -T pdf
	graph --csv real_limits.csv --tmpl ../graph.tmpl > real_limits.graphviz
	dot real_limits.graphviz -o real_limits.pdf -T pdf
	graph --csv real_series.csv --tmpl ../graph.tmpl > real_series.graphviz
	dot real_series.graphviz -o real_series.pdf -T pdf
	graph --csv subset_algebra.csv --tmpl ../graph.tmpl > subset_algebra.graphviz
	dot subset_algebra.graphviz -o subset_algebra.pdf -T pdf
	graph --csv associative_operations.csv --tmpl ../graph.tmpl > associative_operations.graphviz
	dot associative_operations.graphviz -o associative_operations.pdf -T pdf
	graph --csv monotone_sequences.csv --tmpl ../graph.tmpl > monotone_sequences.graphviz
	dot monotone_sequences.graphviz -o monotone_sequences.pdf -T pdf
	graph --csv set_extension.csv --tmpl ../graph.tmpl > set_extension.graphviz
	dot set_extension.graphviz -o set_extension.pdf -T pdf
	graph --csv real_functions.csv --tmpl ../graph.tmpl > real_functions.graphviz
	dot real_functions.graphviz -o real_functions.pdf -T pdf
	graph --csv generated_sigma_algebra.csv --tmpl ../graph.tmpl > generated_sigma_algebra.graphviz
	dot generated_sigma_algebra.graphviz -o generated_sigma_algebra.pdf -T pdf
	graph --csv total_variation.csv --tmpl ../graph.tmpl > total_variation.graphviz
	dot total_variation.graphviz -o total_variation.pdf -T pdf
	graph --csv partitions.csv --tmpl ../graph.tmpl > partitions.graphviz
	dot partitions.graphviz -o partitions.pdf -T pdf
	graph --csv set_examples.csv --tmpl ../graph.tmpl > set_examples.graphviz
	dot set_examples.graphviz -o set_examples.pdf -T pdf
	graph --csv expectation.csv --tmpl ../graph.tmpl > expectation.graphviz
	dot expectation.graphviz -o expectation.pdf -T pdf
	graph --csv extended_real_numbers.csv --tmpl ../graph.tmpl > extended_real_numbers.graphviz
	dot extended_real_numbers.graphviz -o extended_real_numbers.pdf -T pdf
	graph --csv graphs.csv --tmpl ../graph.tmpl > graphs.graphviz
	dot graphs.graphviz -o graphs.pdf -T pdf
	graph --csv intervals.csv --tmpl ../graph.tmpl > intervals.graphviz
	dot intervals.graphviz -o intervals.pdf -T pdf
	graph --csv measure_derivatives.csv --tmpl ../graph.tmpl > measure_derivatives.graphviz
	dot measure_derivatives.graphviz -o measure_derivatives.pdf -T pdf
	graph --csv iterated_integrals.csv --tmpl ../graph.tmpl > iterated_integrals.graphviz
	dot iterated_integrals.graphviz -o iterated_integrals.pdf -T pdf
	graph --csv real_limiting_bounds.csv --tmpl ../graph.tmpl > real_limiting_bounds.graphviz
	dot real_limiting_bounds.graphviz -o real_limiting_bounds.pdf -T pdf
	graph --csv monotone_class.csv --tmpl ../graph.tmpl > monotone_class.graphviz
	dot monotone_class.graphviz -o monotone_class.pdf -T pdf
	graph --csv standard_deviation.csv --tmpl ../graph.tmpl > standard_deviation.graphviz
	dot standard_deviation.graphviz -o standard_deviation.pdf -T pdf
	graph --csv zero_one_law.csv --tmpl ../graph.tmpl > zero_one_law.graphviz
	dot zero_one_law.graphviz -o zero_one_law.pdf -T pdf
	graph --csv families.csv --tmpl ../graph.tmpl > families.graphviz
	dot families.graphviz -o families.pdf -T pdf
	graph --csv sigma_algebra_independence.csv --tmpl ../graph.tmpl > sigma_algebra_independence.graphviz
	dot sigma_algebra_independence.graphviz -o sigma_algebra_independence.pdf -T pdf
	graph --csv ordered_pairs.csv --tmpl ../graph.tmpl > ordered_pairs.graphviz
	dot ordered_pairs.graphviz -o ordered_pairs.pdf -T pdf
	graph --csv solving_equations.csv --tmpl ../graph.tmpl > solving_equations.graphviz
	dot solving_equations.graphviz -o solving_equations.pdf -T pdf
	graph --csv trees.csv --tmpl ../graph.tmpl > trees.graphviz
	dot trees.graphviz -o trees.pdf -T pdf
	graph --csv direct_products.csv --tmpl ../graph.tmpl > direct_products.graphviz
	dot direct_products.graphviz -o direct_products.pdf -T pdf
	graph --csv function_inverses.csv --tmpl ../graph.tmpl > function_inverses.graphviz
	dot function_inverses.graphviz -o function_inverses.pdf -T pdf
	graph --csv operations.csv --tmpl ../graph.tmpl > operations.graphviz
	dot operations.graphviz -o operations.pdf -T pdf
	graph --csv relations.csv --tmpl ../graph.tmpl > relations.graphviz
	dot relations.graphviz -o relations.pdf -T pdf
	graph --csv functions.csv --tmpl ../graph.tmpl > functions.graphviz
	dot functions.graphviz -o functions.pdf -T pdf
	graph --csv measurable_functions.csv --tmpl ../graph.tmpl > measurable_functions.graphviz
	dot measurable_functions.graphviz -o measurable_functions.pdf -T pdf
	graph --csv rational_numbers.csv --tmpl ../graph.tmpl > rational_numbers.graphviz
	dot rational_numbers.graphviz -o rational_numbers.pdf -T pdf
	graph --csv measurable_sections.csv --tmpl ../graph.tmpl > measurable_sections.graphviz
	dot measurable_sections.graphviz -o measurable_sections.pdf -T pdf
	graph --csv monotone_algebra.csv --tmpl ../graph.tmpl > monotone_algebra.graphviz
	dot monotone_algebra.graphviz -o monotone_algebra.pdf -T pdf
	graph --csv natural_numbers.csv --tmpl ../graph.tmpl > natural_numbers.graphviz
	dot natural_numbers.graphviz -o natural_numbers.pdf -T pdf
	graph --csv product_sections.csv --tmpl ../graph.tmpl > product_sections.graphviz
	dot product_sections.graphviz -o product_sections.pdf -T pdf
	graph --csv random_variable_independence.csv --tmpl ../graph.tmpl > random_variable_independence.graphviz
	dot random_variable_independence.graphviz -o random_variable_independence.pdf -T pdf
	graph --csv simple_functions.csv --tmpl ../graph.tmpl > simple_functions.graphviz
	dot simple_functions.graphviz -o simple_functions.pdf -T pdf
	graph --csv natural_order.csv --tmpl ../graph.tmpl > natural_order.graphviz
	dot natural_order.graphviz -o natural_order.pdf -T pdf
	graph --csv subset_system.csv --tmpl ../graph.tmpl > subset_system.graphviz
	dot subset_system.graphviz -o subset_system.pdf -T pdf
	graph --csv order_relations.csv --tmpl ../graph.tmpl > order_relations.graphviz
	dot order_relations.graphviz -o order_relations.pdf -T pdf
	graph --csv product_under_independence.csv --tmpl ../graph.tmpl > product_under_independence.graphviz
	dot product_under_independence.graphviz -o product_under_independence.pdf -T pdf
	graph --csv random_variable_moments.csv --tmpl ../graph.tmpl > random_variable_moments.graphviz
	dot random_variable_moments.graphviz -o random_variable_moments.pdf -T pdf
	graph --csv metrics.csv --tmpl ../graph.tmpl > metrics.graphviz
	dot metrics.graphviz -o metrics.pdf -T pdf
	graph --csv random_variable_sigma_algebra.csv --tmpl ../graph.tmpl > random_variable_sigma_algebra.graphviz
	dot random_variable_sigma_algebra.graphviz -o random_variable_sigma_algebra.pdf -T pdf
	graph --csv almost_everywhere_measurability.csv --tmpl ../graph.tmpl > almost_everywhere_measurability.graphviz
	dot almost_everywhere_measurability.graphviz -o almost_everywhere_measurability.pdf -T pdf
	graph --csv element_functions.csv --tmpl ../graph.tmpl > element_functions.graphviz
	dot element_functions.graphviz -o element_functions.pdf -T pdf
	graph --csv measure_vector_space.csv --tmpl ../graph.tmpl > measure_vector_space.graphviz
	dot measure_vector_space.graphviz -o measure_vector_space.pdf -T pdf
	graph --csv equivalence_relations.csv --tmpl ../graph.tmpl > equivalence_relations.graphviz
	dot equivalence_relations.graphviz -o equivalence_relations.pdf -T pdf
	graph --csv independent_identically_distributed.csv --tmpl ../graph.tmpl > independent_identically_distributed.graphviz
	dot independent_identically_distributed.graphviz -o independent_identically_distributed.pdf -T pdf
	graph --csv inverse_elements.csv --tmpl ../graph.tmpl > inverse_elements.graphviz
	dot inverse_elements.graphviz -o inverse_elements.pdf -T pdf
	graph --csv simple_integral_additivity.csv --tmpl ../graph.tmpl > simple_integral_additivity.graphviz
	dot simple_integral_additivity.graphviz -o simple_integral_additivity.pdf -T pdf
	graph --csv topological_spaces.csv --tmpl ../graph.tmpl > topological_spaces.graphviz
	dot topological_spaces.graphviz -o topological_spaces.pdf -T pdf
	graph --csv monotone_class_theorem.csv --tmpl ../graph.tmpl > monotone_class_theorem.graphviz
	dot monotone_class_theorem.graphviz -o monotone_class_theorem.pdf -T pdf
	graph --csv norms.csv --tmpl ../graph.tmpl > norms.graphviz
	dot norms.graphviz -o norms.pdf -T pdf
	graph --csv section_measures.csv --tmpl ../graph.tmpl > section_measures.graphviz
	dot section_measures.graphviz -o section_measures.pdf -T pdf
	graph --csv sequences.csv --tmpl ../graph.tmpl > sequences.graphviz
	dot sequences.graphviz -o sequences.pdf -T pdf
	graph --csv functionals.csv --tmpl ../graph.tmpl > functionals.graphviz
	dot functionals.graphviz -o functionals.pdf -T pdf
	graph --csv rings.csv --tmpl ../graph.tmpl > rings.graphviz
	dot rings.graphviz -o rings.pdf -T pdf
	graph --csv simple_integral_homogeneity.csv --tmpl ../graph.tmpl > simple_integral_homogeneity.graphviz
	dot simple_integral_homogeneity.graphviz -o simple_integral_homogeneity.pdf -T pdf
