all: ../graph.tmpl ../clip.go 
	graph --csv fields.csv --tmpl ../graph.tmpl > fields.graphviz
	dot fields.graphviz -o fields.pdf -T pdf
	graph --csv linear_independence.csv --tmpl ../graph.tmpl > linear_independence.graphviz
	dot linear_independence.graphviz -o linear_independence.pdf -T pdf
	graph --csv natural_numbers.csv --tmpl ../graph.tmpl > natural_numbers.graphviz
	dot natural_numbers.graphviz -o natural_numbers.pdf -T pdf
	graph --csv ordered_pairs.csv --tmpl ../graph.tmpl > ordered_pairs.graphviz
	dot ordered_pairs.graphviz -o ordered_pairs.pdf -T pdf
	graph --csv set_extension.csv --tmpl ../graph.tmpl > set_extension.graphviz
	dot set_extension.graphviz -o set_extension.pdf -T pdf
	graph --csv algebras.csv --tmpl ../graph.tmpl > algebras.graphviz
	dot algebras.graphviz -o algebras.pdf -T pdf
	graph --csv function_composition.csv --tmpl ../graph.tmpl > function_composition.graphviz
	dot function_composition.graphviz -o function_composition.pdf -T pdf
	graph --csv functional_analysis.csv --tmpl ../graph.tmpl > functional_analysis.graphviz
	dot functional_analysis.graphviz -o functional_analysis.pdf -T pdf
	graph --csv metric_continuity.csv --tmpl ../graph.tmpl > metric_continuity.graphviz
	dot metric_continuity.graphviz -o metric_continuity.pdf -T pdf
	graph --csv metric_convergence.csv --tmpl ../graph.tmpl > metric_convergence.graphviz
	dot metric_convergence.graphviz -o metric_convergence.pdf -T pdf
	graph --csv norm_examples.csv --tmpl ../graph.tmpl > norm_examples.graphviz
	dot norm_examples.graphviz -o norm_examples.pdf -T pdf
	graph --csv norms.csv --tmpl ../graph.tmpl > norms.graphviz
	dot norms.graphviz -o norms.pdf -T pdf
	graph --csv supremum_norm.csv --tmpl ../graph.tmpl > supremum_norm.graphviz
	dot supremum_norm.graphviz -o supremum_norm.pdf -T pdf
	graph --csv vectors.csv --tmpl ../graph.tmpl > vectors.graphviz
	dot vectors.graphviz -o vectors.pdf -T pdf
	graph --csv sequences.csv --tmpl ../graph.tmpl > sequences.graphviz
	dot sequences.graphviz -o sequences.pdf -T pdf
	graph --csv bounded_functions.csv --tmpl ../graph.tmpl > bounded_functions.graphviz
	dot bounded_functions.graphviz -o bounded_functions.pdf -T pdf
	graph --csv bounded_linear_norm.csv --tmpl ../graph.tmpl > bounded_linear_norm.graphviz
	dot bounded_linear_norm.graphviz -o bounded_linear_norm.pdf -T pdf
	graph --csv functionals.csv --tmpl ../graph.tmpl > functionals.graphviz
	dot functionals.graphviz -o functionals.pdf -T pdf
	graph --csv integer_numbers.csv --tmpl ../graph.tmpl > integer_numbers.graphviz
	dot integer_numbers.graphviz -o integer_numbers.pdf -T pdf
	graph --csv linear_combinations.csv --tmpl ../graph.tmpl > linear_combinations.graphviz
	dot linear_combinations.graphviz -o linear_combinations.pdf -T pdf
	graph --csv real_continuity.csv --tmpl ../graph.tmpl > real_continuity.graphviz
	dot real_continuity.graphviz -o real_continuity.pdf -T pdf
	graph --csv real_convergence.csv --tmpl ../graph.tmpl > real_convergence.graphviz
	dot real_convergence.graphviz -o real_convergence.pdf -T pdf
	graph --csv sets.csv --tmpl ../graph.tmpl > sets.graphviz
	dot sets.graphviz -o sets.pdf -T pdf
	graph --csv vector_bases.csv --tmpl ../graph.tmpl > vector_bases.graphviz
	dot vector_bases.graphviz -o vector_bases.pdf -T pdf
	graph --csv zero.csv --tmpl ../graph.tmpl > zero.graphviz
	dot zero.graphviz -o zero.pdf -T pdf
	graph --csv absolute_value.csv --tmpl ../graph.tmpl > absolute_value.graphviz
	dot absolute_value.graphviz -o absolute_value.pdf -T pdf
	graph --csv bounded_linear_functions.csv --tmpl ../graph.tmpl > bounded_linear_functions.graphviz
	dot bounded_linear_functions.graphviz -o bounded_linear_functions.pdf -T pdf
	graph --csv complete_metric_spaces.csv --tmpl ../graph.tmpl > complete_metric_spaces.graphviz
	dot complete_metric_spaces.graphviz -o complete_metric_spaces.pdf -T pdf
	graph --csv real_numbers.csv --tmpl ../graph.tmpl > real_numbers.graphviz
	dot real_numbers.graphviz -o real_numbers.pdf -T pdf
	graph --csv real_uniform_continuity.csv --tmpl ../graph.tmpl > real_uniform_continuity.graphviz
	dot real_uniform_continuity.graphviz -o real_uniform_continuity.pdf -T pdf
	graph --csv set_specification.csv --tmpl ../graph.tmpl > set_specification.graphviz
	dot set_specification.graphviz -o set_specification.pdf -T pdf
	graph --csv vector_space_dimension.csv --tmpl ../graph.tmpl > vector_space_dimension.graphviz
	dot vector_space_dimension.graphviz -o vector_space_dimension.pdf -T pdf
	graph --csv complex_numbers.csv --tmpl ../graph.tmpl > complex_numbers.graphviz
	dot complex_numbers.graphviz -o complex_numbers.pdf -T pdf
	graph --csv metric_space_examples.csv --tmpl ../graph.tmpl > metric_space_examples.graphviz
	dot metric_space_examples.graphviz -o metric_space_examples.pdf -T pdf
	graph --csv subsets.csv --tmpl ../graph.tmpl > subsets.graphviz
	dot subsets.graphviz -o subsets.pdf -T pdf
	graph --csv bounded_linear_continuous.csv --tmpl ../graph.tmpl > bounded_linear_continuous.graphviz
	dot bounded_linear_continuous.graphviz -o bounded_linear_continuous.pdf -T pdf
	graph --csv complete_norm_spaces.csv --tmpl ../graph.tmpl > complete_norm_spaces.graphviz
	dot complete_norm_spaces.graphviz -o complete_norm_spaces.pdf -T pdf
	graph --csv functions.csv --tmpl ../graph.tmpl > functions.graphviz
	dot functions.graphviz -o functions.pdf -T pdf
	graph --csv groups.csv --tmpl ../graph.tmpl > groups.graphviz
	dot groups.graphviz -o groups.pdf -T pdf
	graph --csv norm_metrics.csv --tmpl ../graph.tmpl > norm_metrics.graphviz
	dot norm_metrics.graphviz -o norm_metrics.pdf -T pdf
	graph --csv linear_functions.csv --tmpl ../graph.tmpl > linear_functions.graphviz
	dot linear_functions.graphviz -o linear_functions.pdf -T pdf
	graph --csv operations.csv --tmpl ../graph.tmpl > operations.graphviz
	dot operations.graphviz -o operations.pdf -T pdf
	graph --csv solving_equations.csv --tmpl ../graph.tmpl > solving_equations.graphviz
	dot solving_equations.graphviz -o solving_equations.pdf -T pdf
	graph --csv span.csv --tmpl ../graph.tmpl > span.graphviz
	dot span.graphviz -o span.pdf -T pdf
	graph --csv complex_inner_products.csv --tmpl ../graph.tmpl > complex_inner_products.graphviz
	dot complex_inner_products.graphviz -o complex_inner_products.pdf -T pdf
	graph --csv egoprox_sequences.csv --tmpl ../graph.tmpl > egoprox_sequences.graphviz
	dot egoprox_sequences.graphviz -o egoprox_sequences.pdf -T pdf
	graph --csv inner_product_norms.csv --tmpl ../graph.tmpl > inner_product_norms.graphviz
	dot inner_product_norms.graphviz -o inner_product_norms.pdf -T pdf
	graph --csv metrics.csv --tmpl ../graph.tmpl > metrics.graphviz
	dot metrics.graphviz -o metrics.pdf -T pdf
	graph --csv real_sequences.csv --tmpl ../graph.tmpl > real_sequences.graphviz
	dot real_sequences.graphviz -o real_sequences.pdf -T pdf
	graph --csv relations.csv --tmpl ../graph.tmpl > relations.graphviz
	dot relations.graphviz -o relations.pdf -T pdf
	graph --csv set_examples.csv --tmpl ../graph.tmpl > set_examples.graphviz
	dot set_examples.graphviz -o set_examples.pdf -T pdf
