real_integral_dominated_convergence.pdf: ../*.tex ../trademark.pdf *.tex
	pdflatex real_integral_dominated_convergence.tex
	make defs

make:
	make real_integral_dominated_convergence.pdf

open: real_integral_dominated_convergence.pdf
	open real_integral_dominated_convergence.pdf

defs: real_integral_dominated_convergence.tex
	defs real_integral_dominated_convergence.tex
