real_integral_limit_inferior_bound.pdf: ../*.tex ../trademark.pdf *.tex
	pdflatex real_integral_limit_inferior_bound.tex
	make defs

make:
	make real_integral_limit_inferior_bound.pdf

open: real_integral_limit_inferior_bound.pdf
	open real_integral_limit_inferior_bound.pdf

defs: real_integral_limit_inferior_bound.tex
	defs real_integral_limit_inferior_bound.tex
