almost_everywhere_measurability.pdf: ../*.tex ../trademark.pdf *.tex
	pdflatex almost_everywhere_measurability.tex
	make defs

make:
	make almost_everywhere_measurability.pdf

open: almost_everywhere_measurability.pdf
	open almost_everywhere_measurability.pdf

defs: almost_everywhere_measurability.tex
	defs almost_everywhere_measurability.tex
