simple_integral_linearity.pdf: ../*.tex ../trademark.pdf *.tex
	pdflatex simple_integral_linearity.tex
	make defs

make:
	make simple_integral_linearity.pdf

open: simple_integral_linearity.pdf
	open simple_integral_linearity.pdf

defs: simple_integral_linearity.tex
	defs simple_integral_linearity.tex
