topological_sigma_algebra.pdf: ../*.tex ../trademark.pdf *.tex
	pdflatex topological_sigma_algebra.tex
	make defs

make:
	make topological_sigma_algebra.pdf

open: topological_sigma_algebra.pdf
	open topological_sigma_algebra.pdf

defs: topological_sigma_algebra.tex
	defs topological_sigma_algebra.tex
