supremum_norm_complete.pdf: ../*.tex ../trademark.pdf *.tex
	pdflatex supremum_norm_complete.tex
	make defs

make:
	make supremum_norm_complete.pdf

open: supremum_norm_complete.pdf
	open supremum_norm_complete.pdf

defs: supremum_norm_complete.tex
	defs supremum_norm_complete.tex
