simple_integral_homogeneity.pdf: ../*.tex ../trademark.pdf *.tex
	pdflatex simple_integral_homogeneity.tex
	make defs

make:
	make simple_integral_homogeneity.pdf

open: simple_integral_homogeneity.pdf
	open simple_integral_homogeneity.pdf

defs: simple_integral_homogeneity.tex
	defs simple_integral_homogeneity.tex
