real_integral_limit_theorems.pdf: ../*.tex ../trademark.pdf *.tex
	pdflatex real_integral_limit_theorems.tex
	make defs

make:
	make real_integral_limit_theorems.pdf

open: real_integral_limit_theorems.pdf
	open real_integral_limit_theorems.pdf

defs: real_integral_limit_theorems.tex
	defs real_integral_limit_theorems.tex
