set_operations.pdf: set_operations.tex
	pdflatex set_operations.tex
	make defs

make:
	make set_operations.pdf

open: set_operations.pdf
	open set_operations.pdf

defs: set_operations.tex
	defs set_operations.tex
