measurable_function_operations.pdf: ../*.tex ../trademark.pdf *.tex
	pdflatex measurable_function_operations.tex
	make defs

make:
	make measurable_function_operations.pdf

open: measurable_function_operations.pdf
	open measurable_function_operations.pdf

defs: measurable_function_operations.tex
	defs measurable_function_operations.tex
