.PHONY: make

# accidentally run too many times
# make:
# 	bbk_sheets
#
# below will do pretty well, will mis sheet ref but so be it
# for now need to tend to do this for tex and for lit
# find "." -name "*.lit" | xargs sed -i -e "s/:<old sheet name>/:<new sheet name>/g"
