make:
	go install check/bbk_check.go
	go install clip/bbk_clip.go
	go install implicit_graph/bbk_implicit_graph.go
	go install search/bbk_search.go
	go install serve/bbk_serve.go
	go install bbk/bbk.go
