make:
	go install graph/bbk_graph.go
	go install clip/bbk_clip.go
	go install check/bbk_check.go
	go install implicit_graph/bbk_implicit_graph.go
	go install compile_screen/bbk_compile_screen.go
	go install sheet/bbk_sheet.go
