make:
	go install check/bbk_check.go
	go install clip/bbk_clip.go
	go install compile_screen/bbk_compile_screen.go
	go install graph/bbk_graph.go
	go install implicit_graph/bbk_implicit_graph.go
	go install search/bbk_search.go
	go install serve/bbk_serve.go
	go install sheet/bbk_sheet.go
	go install sheets/bbk_sheets.go
	go install all/bbk_all.go
