monotone_class_theorem.pdf: ../*.tex ../trademark.pdf *.tex
	pdflatex monotone_class_theorem.tex
	make defs

make:
	make monotone_class_theorem.pdf

open: monotone_class_theorem.pdf
	open monotone_class_theorem.pdf

defs: monotone_class_theorem.tex
	defs monotone_class_theorem.tex
